name: Workflow using the k6 run action
on:
  push:

jobs:
  protocol:
    runs-on: ubuntu-latest
    env:
      K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@main
      - uses: ./
        continue-on-error: true
        with:
          path: |
            ./dev/protocol*.js
          flags: --vus 10 --duration 30s
          parallel: true
          cloud-run-locally: false
  protocol-without-flags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@main
      - uses: ./
        continue-on-error: true
        with:
          path: |
            ./dev/protocol*.js
  show-complete-k6-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@main
      - uses: ./
        with:
          path: |
            ./dev/protocol.js
          flags: --vus 10 --duration 30s
          debug: true
  verify-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@main
      - uses: ./
        continue-on-error: true
        with:
          path: |
            ./dev/verify-script-tests/**.js
          only-verify-scripts: true
  env-var-test:
    runs-on: ubuntu-latest
    env:
      TEST_SYSTEM_ENV_VAR: "test-system-env-var-value"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@main
      - uses: ./
        with:
          path: |
            ./dev/env-var-test.js
          flags: --vus 1 --duration 1s --env TEST_FLAG_ENV_VAR=test-flag-env-var-value -e TEST_SYSTEM_ENV_VAR_E=test-cli-e-env-var-value
